### ISSUE TITLE
when you give the graph generator a target_n larger than the original

### ISSUE THREAD

**Issue by abitofalchemy** [satyakisikdar/VRG#3]
I have seen that the target_n larger than the original graph can go in to a while loop that never ends. Have you seen that?

**Comment by abitofalchemy** [comment]
this issue is addressed by the tolerance bounds.

**Comment by satyakisikdar** [comment]
Thanks for bringing this issue to my attention. I've added a TimeoutError exception if the generation fails even after 1000 tries.
